### ISSUE TITLE
Автообновление

### ISSUE THREAD

**Issue by 3uHa** [lazyphpdev/DLE-Moonwalk#2]
Пробовал обе команды вызова файла dle_moonwalk_cron.php по cron. Первая работает, но не поднимает новости, а вторая запускается с ошибкой. Если через адресную строку запустить скрипт, то он начнёт автообновлять новости. Поробовал поставить на cron запуск ссылки, тоже не работает. ("site" менял на свой сайт, "API_TOKEN" менял на свой токен)

**Comment by lazyphpdev** [comment]
Пожалуйста скиньте свои настройки модуля в telegram: https://t.me/lazyphpdev или на почту: support@punpun.name
