### ISSUE TITLE
Не проставляет тайтл для мультфильмов

### ISSUE THREAD

**Issue by foxrus** [lazyphpdev/DLE-Moonwalk#32]
Для фильмов и сериалов, тайтл заполняется, а в мультфильмах тайтл выглядит примерно вот так - Смолфут>>Тайтл сайта

**Comment by lazyphpdev** [comment]
Тайтл это Мета тайтл или Название новости?

**Comment by foxrus** [comment]
Мета тайтл

**Comment by lazyphpdev** [comment]
При заполнении новости или автообновлении?

**Comment by foxrus** [comment]
При обновлении

**Comment by foxrus** [comment]
Когда я добавляю новость, то оставляю качество «Трейлер», и через несколько минут новость обновляется, проставляется качество, и меняется мета тайтл. Для фильмов и сериалов все отлично работает, а в мультфильмах меняется только качество. Если зайти в редактирование мультфильма, то тайтл вообще пустой

**Comment by lazyphpdev** [comment]
Проверил, для мультсериалов проблем нет. А для мультифильмов мета тайтл проставляется при добавлении новости. При автообновлении метатайтл там не меняется.

**Comment by foxrus** [comment]
Извиняюсь, намудрил с парсером кинопоиска. Сначала заполняю новость с помощью этого модуля, а потом до-заполняю парсером кинопоиска, и так как для мультфильмов не был выставлен мета тайтл, то он его просто удалял и оставлял пустое поле.
Можешь удалять ветку.
