### ISSUE TITLE
ссылка на фильм удаляется

### ISSUE THREAD

**Issue by Studentul** [lazyphpdev/DLE-Moonwalk#47]
---
@lazyphpdev не забудь посмотреть этот тиккет :ticket:

Здраствуите, при обновлении фильма, удаляется ссылка на фильм из доп поля и меняет качество в web-dl однако фильмы есть в HD качестве.
У некоторых сериалов меняет качество на трейлер.
версия 2.0.1

**Comment by MGHaze** [comment]
Добавил фильм. Модулем не пользовался, заполнил все данные, кроме ссылки на фильм и качества, через Парсер Кинопоиска. Запустил крон-обновление. Обновились все данные, но ссылка так и не проставилась. Возможно, это та же проблема
