### ISSUE TITLE
Автообновление фильмов

### ISSUE THREAD

**Issue by MGHaze** [lazyphpdev/DLE-Moonwalk#5]
Ради чистоты экперимента удалил у фильма качество и запустил обновление по крону. В итоге качество не заполнилось, как и сам фильм не поднялся

**Comment by MGHaze** [comment]
Так же в блоке у меня сегодня вышло точно больше 30 новых серий, но даты у сериалов обновились только у 10ти. В блоке вывожу только сериалы.

**Comment by lazyphpdev** [comment]
По поводу фильмов.
Дополнительное поле влияет только когда данные в первые заполняются для фильма. То есть, когда в базе модуля данных еще нет. И проверка качества идет именно с базы а не дополнительного поля, что бы не делать лишних запросов и нагрузки.

По поводу сериалов.
Это после первого запуска было или уже второй запуск?

**Comment by MGHaze** [comment]
Даже не скажу, какой запуск. По крону стоит каждый час. Беру конкретный сериал, последний в блоке. В данный момент в блоке показывает 3 сезон 5 серию. По факту открываю новость, а там до сих пор 2 сезон 18 серия (дата редактирования 15 марта 2018). 

Но в тоже время какие-то сериалы поднимает. Может мне очистить базу как-то? И заново запустить крон? Могу скинуть в телегу сайт, если надо

**Comment by MGHaze** [comment]
Автообновление не проставляет озвучку для фильмов?
