### ISSUE TITLE
Запись озвучек

### ISSUE THREAD

**Issue by morefilms** [lazyphpdev/DLE-Moonwalk#51]
---
@lazyphpdev не забудь посмотреть этот тиккет :ticket:
Если у сериала было несколько озвучек, а потом добавилась еще одна, то она не дописывается в допполе
Видно на примере сериала Dogs of Berlin, вчера вышла озвучка Newstudio http://picplus.ru/img/1812/30/a9bd75ad.png
Но в допполе переводов только то, что было добавлено изначально http://picplus.ru/img/1812/30/eac903c4.png

**Comment by lazyphpdev** [comment]
Это не баг, оно запишется тогда когда выйдет новая серия. Иначе зачем перезаписывать по 100 раз данные.
