### ISSUE TITLE
Неверный парсинг сезона

### ISSUE THREAD

**Issue by morefilms** [lazyphpdev/DLE-Moonwalk#53]
---
@lazyphpdev не забудь посмотреть этот тиккет :ticket:
В сериале с кп айди 1209251 модуль парсит как 30 сезон, хотя есть всего 1.

**Comment by lazyphpdev** [comment]
@morefilms это ошибка в API Moonwalk, передам для устранения проблемы с этим с сериалом.
Используйте тег {translator-all} он записан как в документации так и в админ панели модуля
`[tag-translator-all]{translator-all}[/tag-translator-all]	Все доступные озвучки`

**Comment by morefilms** [comment]
проблема решена, спасибо
