### ISSUE TITLE
Не "дружит" с модулем TrailerDP

### ISSUE THREAD

**Issue by 3uHa** [lazyphpdev/DLE-Moonwalk#56]
---
@lazyphpdev не забудь посмотреть этот тиккет :ticket:
Только недавно заметил, что пропали кнопки поиска и просмотра трейлера у модуля TrailerDP v.2.0 от Sistemos. После проверки было выявлено, что они не отображаются после установки и настройки этого модуля.

**Comment by lazyphpdev** [comment]
@lazyphpdev пусть тогда Sistemos правит свой модуль.
