### ISSUE TITLE
Запись озвучек

### ISSUE THREAD

**Issue by morefilms** [lazyphpdev/DLE-Moonwalk#57]
---
@lazyphpdev не забудь посмотреть этот тиккет :ticket:
Запись студий озвучивших сериал в допполе происходит все-таки с каким-то сбоем. Прошелся по нескольким десяткам сериалов и в очень! многих новостях в допполе записаны не все студии. В некоторых новостях у волков есть 5-7 переводов, в допполе записан только один. В некоторых может быть из 5 переводов записано в допполе 4, только одного нету. А может у волков быть 2 перевода, в допполе один. т.е. отследить какой-то привязки не удалось, но запись происходит точно не верно.
Нужна запись именно в допполе, для возможности сортировать и фильтровать по студиям, в замену тег, к сожалению, не подойдет

**Comment by morefilms** [comment]
+ еще момент, если для сериала есть озвучка только "многоголосый закадровый", то она пишется в БД, а если "многоголосый закадровый" и еще студии, то "многоголосый закадровый" не пишется в допполе, пишутся только студии. 
http://picplus.ru/img/1901/11/f6424da7.png
http://picplus.ru/img/1901/11/4c6097d4.png

**Comment by lazyphpdev** [comment]
@morefilms предоставьте скриншоты своих настроек

**Comment by morefilms** [comment]
файл настроек http://multi-up.com/1220113

**Comment by lazyphpdev** [comment]
@morefilms id кинопоиска этого сериала

**Comment by morefilms** [comment]
вчера чистил допполе озвучек и таблицу dle_moonwalk, далее работал крон, вроде проставилось все нормально, кроме нюанса с "многоголосый закадровый" что выше описал.
Сегодня для сериала 818284 указана только Newstudio
для 1111888 - только Coldfilm
для 968215 - только Newstudio
и таких сериалов много...
хотя для все их есть 2 и более озвучки
