### ISSUE TITLE
Дата новости

### ISSUE THREAD

**Issue by morefilms** [lazyphpdev/DLE-Moonwalk#8]
- [x] 1. Сделайте, пожалуйста, возможность глобально отключить автоподнятие, очень удобно при установке модуля, что бы он не поднимая все новости заполнил у них поля.
- [x] 2. И еще было бы хорошо уметь ставить дату новости с Moonwalk и дату для блока с Moonwalk

**Comment by MGHaze** [comment]
А это не то? https://i.imgur.com/6HHqveo.png

**Comment by morefilms** [comment]
Вы правы - для блока это именно то, что нужно. Но хотелось бы такое еще и для даты самой новости
