### ISSUE TITLE
Повторы в блоке

### ISSUE THREAD

**Issue by MGHaze** [lazyphpdev/DLE-Moonwalk#9]
Вчера в блоке появился сериал Мистер Булл с 6 серией и озвучкой Колдфильм. Сегодня, смотрю, тот пропал, но появился он же с другой озвучкой. Можно ли, как в старом модуле, оставлять сериал в покое с первой появившейся озвучкой на своем месте, если не стоит опция вывода всех озвучек?
https://i.imgur.com/onehpmO.png

**Comment by Wodooo** [comment]
В настройках модуля Сериалы - Главные настройки отключить "Поднятие новости по всем озвучкам"

**Comment by MGHaze** [comment]
Я же в первом сообщение сказал, что оно отключено. Да и тогда бы не исчез сериал во вчерашнем дне

**Comment by lazyphpdev** [comment]
Выполнено.
